export enum PermissionsEnum {
  AllowAnyway = 'AllowAnyway',
  ManageRolesAndPermissions = 'manage_roles_and_permissions',
  InviteUsers = 'invite_users',
  ViewUsers = 'view_users',
  DeleteUsers = 'delete_users',
  ViewBotsList = 'view_bots_list',
  ViewBot = 'view_bot',
  CreateBot = 'create_bot',
  UpdateBot = 'update_bot',
  DeleteBot = 'delete_bot',
  ViewChainsList = 'view_chains_list',
  ViewChain = 'view_chain',
  CreateChain = 'create_chain',
  UpdateChain = 'update_chain',
  DeleteChain = 'delete_chain',
  ViewContentsList = 'view_contents_list',
  ViewContent = 'view_content',
  CreateContent = 'create_content',
  UpdateContent = 'update_content',
  DeleteContent = 'delete_content',
  ViewChannelsList = 'view_channels_list',
  ViewChannel = 'view_channel',
  CreateChannel = 'create_channel',
  UpdateChannel = 'update_channel',
  DeleteChannel = 'delete_channel',
  ViewPostsList = 'view_posts_list',
  ViewPost = 'view_post',
  CreatePost = 'create_post',
  UpdatePost = 'update_post',
  DeletePost = 'delete_post',
  ViewLanguagesList = 'view_languages_list',
  ViewCategoriesList = 'view_categories_list',
  ViewCategory = 'view_category',
  CreateCategory = 'create_category',
  UpdateCategory = 'update_category',
  DeleteCategory = 'delete_category',
  ViewCharactersList = 'view_characters_list',
  ViewCharacter = 'view_character',
  CreateCharacter = 'create_character',
  UpdateCharacter = 'update_character',
  DeleteCharacter = 'delete_character',
  ViewSchedule = 'view_schedule',
  CreateSchedule = 'create_schedule',
  UpdateSchedule = 'update_schedule',
  DeleteSchedule = 'delete_schedule',
  ManageChats = 'manage_chats',
  UpdateUsers = 'update_users',
  ViewCountriesList = 'view_countries_list',
  ViewCountry = 'view_country',
  DeleteSubject = 'delete_subject',
  UpdateSubject = 'update_subject',
  CreateSubject = 'create_subject',
  ViewSubject = 'view_subject',
  ViewSubjectsList = 'view_subjects_list',


}

export const NESTED_URL_BY_PERMISSIONS = {
  [PermissionsEnum.ViewBotsList]: 'bots',
  [PermissionsEnum.ViewPostsList]: 'posts',
  [PermissionsEnum.ManageChats]: 'messenger',
  [PermissionsEnum.ViewChannelsList]: 'channels',
  [PermissionsEnum.ViewCategoriesList]: 'dictionaries/categories',
  [PermissionsEnum.ViewLanguagesList]: 'dictionaries/languages',
  [PermissionsEnum.ViewCharactersList]: 'dictionaries/characters',
  [PermissionsEnum.ViewCharactersList]: 'dictionaries/countries',
  [PermissionsEnum.ViewCharactersList]: 'dictionaries/subjects',
  [PermissionsEnum.ViewCharactersList]: 'settings/permissions',
  [PermissionsEnum.ViewCharactersList]: 'settings/roles',
  [PermissionsEnum.ViewCharactersList]: 'settings/users',
};
